language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-19mode   # Rubinius in 1.9 mode
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
